[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- SULAP JADI N16R8 & PARTISI BESAR ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv

build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_GFX_DISABLE_RGB_PANEL

; --- DOWNLOAD LIBRARY OTOMATIS ---
lib_deps = 
    moononournation/GFX Library for Arduino @ 1.4.7   ; <--- KUNCI FIX ERROR (Turun ke 1.4.7)
    bitbank2/AnimatedGIF @ ^2.1.0